export {default as Home} from './Home/home'
export {default as Login} from './Login/login'
export {default as Register} from './Register/register'
export {default as Dashboard} from './User/dashboard'
export {default as NavbarX} from './navbarX/navbarX'
export {default as MyCourses} from './User/my courses/myCourses'
export {default as MyClass} from './User/myClass'
export {default as Daily} from './User/daily'
export {default as HomeWork} from './User/homeWork'
export {default as Chats} from './User/chats'
export {default as AboutUser} from './User/aboutUser/aboutUser'
export {default as SchoolGallery} from './User/school gallery/schoolGallery'
export {default as LoadingSpinner} from './ui/spinner'